autoInstallPeers: true
allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  less: false
  lmdb: false
  msgpackr-extract: false
  nx: true
  unrs-resolver: false
  '@nestjs/core': false
  workerd: false
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  bcrypt: set this to true or false
